// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvipmquzrngcsibqkbcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2aXBtcXV6cm5nY3NpYnFrYmNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjMxNTksImV4cCI6MjA2NTM5OTE1OX0.8EkWmD_EymOOq5bhGqbFnlwF-u7dFAj92vF0qAZmLuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);